tf: fix case in register gradient (#378)
* tf: fix case in register gradient

register gradient operation for "BytepsPushPull" instead of
"BytePSPushPull". This matches the case in REGISTER_OP. Fixes the
following error:

  LookupError: gradient registry has no entry for: BytepsPushPull

Signed-off-by: Yulu Jia <yulu.jia@bytedance.com>