torch.autograd.profiler.profile() keyword argument
torch.autograd.profiler.profile() will not take 3 positional argumens (self, False, True) when enabled=False with the latest change to PyTorch source code.
This means that:
bpslaunch python benchmark_byteps.py --fp16-pushpull
fails with:
with torch.autograd.profiler.profile(False, True) as prof:                                                                               
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given
To fix this:
Use keyword arguments (enabled=enable_profiling, use_cuda=True)